---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.shop.name }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.apps.shop.name }}
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.shop.name }}-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.apps.shop.storage }}
  storageClassName: {{ .Values.global.storageClass }}
