apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app: metallb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      labels:
        app: metallb
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: quay.io/metallb/controller:v0.13.10
        args:
        - controller
