apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.blog.name }}-deploy
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.apps.blog.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.blog.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apps.blog.name }}
    spec:
      containers:
        - name: {{ .Values.apps.blog.name }}-container
          image: {{ .Values.apps.blog.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Values.apps.blog.name }}-volume
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: {{ .Values.apps.blog.name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.apps.blog.name }}-pvc
